In [1]:
import numpy as np
import tensorflow as tf



In [3]:
a = np.arange(24) #np.arange用法



In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
tf.reshape(a,(12,2))   #tf.reshape用法

<tf.Tensor 'Reshape:0' shape=(12, 2) dtype=int32>

In [3]:
sess=tf.Session()
sess.run(tf.reshape(a,(12,2)))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
sess.run(tf.reshape(a,[6,4]))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
sess.run(tf.reshape(a,[6,-1]))  #-1自动计算后一个维度


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
sess.run(tf.reshape(a,[-1,4]))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
sess.run(tf.reshape(a,[4,-1]))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
sess.run(tf.reshape(a,[4,3,2]))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [4]:
a = np.arange(24)


b = [1,2,3]


c= tf.reshape(a,[6,4])
sess.run(c)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
print(sess.run(tf.shape(a)))
print(sess.run(tf.shape(b)))
print(sess.run(tf.shape(c)))

[24]
[3]
[6 4]


In [23]:
a.get_shape() #说明x.get_shape()中,x只能是tensor,否则报错,并且返回的是一个元组,可以分别取出行和列

AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

In [24]:
b.get_shape()

AttributeError: 'list' object has no attribute 'get_shape'

In [25]:
c.get_shape() #说明x.get_shape()中,x只能是tensor,否则报错,并且返回的是一个元组,可以分别取出行和列

TensorShape([Dimension(6), Dimension(4)])

In [27]:
c.get_shape()[0].value

6

In [5]:
c.get_shape().as_list()

[6, 4]